// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-addresses.mjs
// Source: ../doppler/Deployments.json
// WARNING: This file is an internal build artifact and is NOT part of the public API.
// WARNING: Do NOT import from this file directly. It should not appear in IDE IntelliSense/suggestions.
// WARNING: If you need Doppler addresses, import from @addresses.ts instead (e.g. use ADDRESSES / getAddresses).

/** @internal */
export type GeneratedDopplerDeployments = Record<string, Record<string, string>>

/** @internal */
export const GENERATED_DOPPLER_DEPLOYMENTS = {
  "130": {
    "Airlock": "0x77EbfBAE15AD200758E9E2E61597c0B07d731254",
    "Bundler": "0x91231cDdD8d6C86Df602070a3081478e074b97b7",
    "DopplerDeployer": "0x0d2f38d807bfAd5C18e430516e10ab560D300caF",
    "DopplerLensQuoter": "0x82Ac010C67f70BACf7655cd8948a4AD92A173CAC",
    "GovernanceFactory": "0x99C94B9Df930E1E21a4E4a2c105dBff21bF5c5aE",
    "LockableUniswapV3Initializer": "0xA3C847eAb58eAa9cbc215C785c9cfBc19CDABD5f",
    "NoOpGovernanceFactory": "0x3AD727ee0FBBb8Ee0920933FdB96F23fD56f1299",
    "NoOpMigrator": "0x917da361072ce968acD810BbfC9B64079426ebf0",
    "StreamableFeesLocker": "0x6ddfED58D238Ca3195E49d8ac3d4cEa6386E5C33",
    "TokenFactory": "0x43d0D97EC9241A8F05A264f94B82A1d2E600f2B3",
    "UniswapV2Migrator": "0xf6023127f6E937091D5B605680056A6D27524bad",
    "UniswapV3Initializer": "0x9F4e56be80f08ba1A2445645EFa6d231E27b43ec",
    "UniswapV4Initializer": "0x4B0EC16Eb40318Ca5A4346f20F04A2285C19675B",
    "UniswapV4Migrator": "0x49F3fBB2dFF7f3d03B622e3b2a6d3F2E6fdB2a5A",
    "UniswapV4MigratorHook": "0x53C050d3B09C80024138165520Bd7c078D9e2000"
  },
  "1301": {
    "Airlock": "0x0d2f38d807bfAd5C18e430516e10ab560D300caF",
    "AirlockMultisig": "0x40Bcb4dDA3BcF7dba30C5d10c31EE2791ed9ddCa",
    "Bundler": "0xED344444633B965cd148F8fFCE3765938A179094",
    "DopplerDeployer": "0x77B5F559EE9cf3bfcf2fFf5731a84332D8eECAC9",
    "DopplerLensQuoter": "0x917da361072ce968acD810BbfC9B64079426ebf0",
    "GovernanceFactory": "0x4225C632b62622Bd7B0A3eC9745C0a866Ff94F6F",
    "LockableUniswapV3Initializer": "0x9dFb775dB7b005d9Dc77DA84D8b2e42C281D0344",
    "NoOpGovernanceFactory": "0x7E5D336A6E9e453c9f02E5102CC039E015Fd8fb8",
    "NoOpMigrator": "0x193F48A45B6025dDeD10bc4BaeEF65c833696387",
    "StreamableFeesLocker": "0x1728E8B3282502f275949109331E070b819B38eA",
    "TokenFactory": "0x82Ac010C67f70BACf7655cd8948a4AD92A173CAC",
    "UniswapV2Migrator": "0x620e3fec244e913d73f2163623b62d02DB69638B",
    "UniswapV3Initializer": "0xE0dC4012AC9C868F09c6e4b20d66ED46D6F258d0",
    "UniswapV4Initializer": "0x70d20cd48791E527036491dc464C8Dc58351Dd93",
    "UniswapV4Migrator": "0xb6D69eAA98E657bEEFF7ca4452768e6f707aa6b1",
    "UniswapV4MigratorHook": "0xFB0671Ec46190b09255776d2D77744fa101Ba500",
    "UniswapV4MulticurveInitializer": "0xac7939F1B4079d55A7fA4DFA314Ac0173A77bA40",
    "UniswapV4MulticurveInitializerHook": "0x11b55A121a38FDab8FAF16f9f1A4f124E3f42d40"
  },
  "4801": {
    "Airlock": "0x5F3bA43D44375286296Cb85F1EA2EBfa25dde731",
    "GovernanceFactory": "0x136191B46478cAB023cbC01a36160C4Aad81677a",
    "TokenFactory": "0x5FBe931dc4B923A7abe4c47aD68d5bF9Eda5B76D",
    "UniswapV2Migrator": "0x8b4C7DB9121FC885689C0A50D5a1429F15AEc2a0",
    "UniswapV3Initializer": "0x9916Ec1c1E0462F6F8f7514e414F06bf001Ac82A",
    "WETH": "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12"
  },
  "8453": {
    "Airlock": "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12",
    "Bundler": "0x136191B46478cAB023cbC01a36160C4Aad81677a",
    "DopplerDeployer": "0x49F3fBB2dFF7f3d03B622e3b2a6d3F2E6fdB2a5A",
    "DopplerLensQuoter": "0x43d0D97EC9241A8F05A264f94B82A1d2E600f2B3",
    "GovernanceFactory": "0xa82c66b6ddEb92089015C3565E05B5c9750b2d4B",
    "LaunchpadGovernanceFactory": "0x40Bcb4dDA3BcF7dba30C5d10c31EE2791ed9ddCa",
    "LockableUniswapV3Initializer": "0xE0dC4012AC9C868F09c6e4b20d66ED46D6F258d0",
    "NoOpGovernanceFactory": "0x3AD727ee0FBBb8Ee0920933FdB96F23fD56f1299",
    "NoOpMigrator": "0x6ddfED58D238Ca3195E49d8ac3d4cEa6386E5C33",
    "StreamableFeesLocker": "0x0A00775D71a42cd33D62780003035e7F5b47bD3A",
    "TokenFactory": "0x4225C632b62622Bd7B0A3eC9745C0a866Ff94F6F",
    "UniswapV2Migrator": "0x5F3bA43D44375286296Cb85F1EA2EBfa25dde731",
    "UniswapV3Initializer": "0xaA47D2977d622DBdFD33eeF6a8276727c52EB4e5",
    "UniswapV4Initializer": "0xED344444633B965cd148F8fFCE3765938A179094",
    "UniswapV4Migrator": "0x166109C4EE7fE69164631Caa937dAA5F5cEbFef0",
    "UniswapV4MigratorHook": "0x45178A8D6d368D612B7552B217802b7F97262000",
    "UniswapV4MulticurveInitializer": "0x65dE470Da664A5be139A5D812bE5FDa0d76CC951",
    "UniswapV4MulticurveInitializerHook": "0x892D3C2B4ABEAAF67d52A7B29783E2161B7CaD40",
    "UniswapV4ScheduledMulticurveInitializer": "0xA36715dA46Ddf4A769f3290f49AF58bF8132ED8E",
    "UniswapV4ScheduledMulticurveInitializerHook": "0x3e342a06f9592459D75721d6956B570F02eF2Dc0"
  },
  "10143": {
    "Airlock": "0xa82c66b6ddEb92089015C3565E05B5c9750b2d4B",
    "AirlockMultisig": "0x3AD727ee0FBBb8Ee0920933FdB96F23fD56f1299",
    "Bundler": "0xf6023127f6E937091D5B605680056A6D27524bad",
    "DopplerDeployer": "0x166109C4EE7fE69164631Caa937dAA5F5cEbFef0",
    "DopplerLensQuoter": "0x2F2BAcd46d3F5c9EE052Ab392b73711dB89129DB",
    "GovernanceFactory": "0x014E1c0bd34f3B10546E554CB33B3293fECDD056",
    "LockableUniswapV3Initializer": "0x99C94B9Df930E1E21a4E4a2c105dBff21bF5c5aE",
    "NoOpGovernanceFactory": "0x094D926A969B3024ca46D2186BF13FD5CDBA9CE2",
    "NoOpMigrator": "0x5CadB034267751a364dDD4d321C99E07A307f915",
    "StreamableFeesLocker": "0x0d2f38d807bfAd5C18e430516e10ab560D300caF",
    "TokenFactory": "0x8AF018e28c273826e6b2d5a99e81c8fB63729b07",
    "UniswapV2Migrator": "0x43d0D97EC9241A8F05A264f94B82A1d2E600f2B3",
    "UniswapV3Initializer": "0x9F4e56be80f08ba1A2445645EFa6d231E27b43ec",
    "UniswapV4Initializer": "0x06FEFD02F0b6d9f57F52cfacFc113665Dfa20F0f",
    "UniswapV4Migrator": "0x4B0EC16Eb40318Ca5A4346f20F04A2285C19675B",
    "UniswapV4MigratorHook": "0x76E1f507592d9856B48482c599732d129eD6a500",
    "UniswapV4MulticurveInitializer": "0xA3C847eAb58eAa9cbc215C785c9cfBc19CDABD5f",
    "UniswapV4MulticurveInitializerHook": "0xFaF16d11737E6552156DD328cD26C530e1da2D40",
    "WETH": "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12"
  },
  "57073": {
    "Airlock": "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12",
    "Bundler": "0x136191B46478cAB023cbC01a36160C4Aad81677a",
    "DopplerDeployer": "0xa82c66b6ddEb92089015C3565E05B5c9750b2d4B",
    "DopplerLensQuoter": "0x8AF018e28c273826e6b2d5a99e81c8fB63729b07",
    "GovernanceFactory": "0xb4deE32EB70A5E55f3D2d861F49Fb3D79f7a14d9",
    "TokenFactory": "0xFAafdE6a5b658684cC5eb0C5c2c755B00A246F45",
    "UniswapV2Migrator": "0x5F3bA43D44375286296Cb85F1EA2EBfa25dde731",
    "UniswapV3Initializer": "0xaA47D2977d622DBdFD33eeF6a8276727c52EB4e5",
    "UniswapV4Initializer": "0x014E1c0bd34f3B10546E554CB33B3293fECDD056"
  },
  "84532": {
    "Airlock": "0x3411306Ce66c9469BFF1535BA955503c4Bde1C6e",
    "AirlockMultisig": "0x852a09C89463D236eea2f097623574f23E225769",
    "BasicMultisig": "0x6f645FA08B7eadAD620CEC85634204b1d7A46DC2",
    "Bundler": "0xab7BACB0d5C2C10152f92D34e07F530EB3CB0Fb1",
    "DopplerDeployer": "0x82D727ffda3F874da802663fC2f3f4b83dC3AAbA",
    "DopplerLensQuoter": "0x4a8d81Db741248a36D9eb3bc6eF648Bf798B47a7",
    "GovernanceFactory": "0x9dBFaaDC8c0cB2c34bA698DD9426555336992e20",
    "LockableUniswapV3Initializer": "0x16AdA5Be50C3c2D94Af5fEae6b539C40A78Ad53c",
    "NoOpGovernanceFactory": "0x7bD798fafC99A3b17E261F8308A8C11B56935ea1",
    "NoOpMigrator": "0xF11066abbd329ac4bBA39455340539322C222eb0",
    "StreamableFeesLocker": "0x3345E557c5C0b474bE1eb4693264008B8562Aa9c",
    "TeamGovernanceFactory": "0x8aF3001ED75F86f4Dd910577ECa9C5dB7CEa765c",
    "TokenFactory": "0x9D8fd79B2a59c5d91ccBd79c3AEb4de56451Bb02",
    "UniswapV2Migrator": "0x04a898f3722c38F9Def707bD17DC78920EFA977C",
    "UniswapV3Initializer": "0x4C3062B9ccFdbCB10353F57C1B59a29d4c5CFa47",
    "UniswapV4Initializer": "0x832e4763dEEcB9941a768f2bBd18583219F018Cc",
    "UniswapV4Migrator": "0xf326D8cdB65A4ad334cFBdD7d3A3CB27Be8b770d",
    "UniswapV4MigratorHook": "0x9D0C38A80647E53D5a8a319B39De2B66B8586500",
    "UniswapV4MulticurveInitializer": "0x8099ef6A2100A5ac02Af275eeD606BABD38a1689",
    "UniswapV4MulticurveInitializerHook": "0xf1A484724e2451d2C0290C946eC0034f057D6d40",
    "UniswapV4ScheduledMulticurveInitializer": "0x5C10D3e14Aae2Ef95619B25E907E013260E832E4",
    "UniswapV4ScheduledMulticurveInitializerHook": "0x5D663F9C993deFf2D17ce4232D75f347df7DADc0",
    "WETH": "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12"
  }
} as const
