// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-addresses.mjs
// Source: ../doppler/Deployments.json
// Timestamp: 2025-10-09T20:02:32.627Z
// WARNING: This file is an internal build artifact and is NOT part of the public API.
// WARNING: Do NOT import from this file directly. It should not appear in IDE IntelliSense/suggestions.
// WARNING: If you need Doppler addresses, import from @addresses.ts instead (e.g. use ADDRESSES / getAddresses).

export type GeneratedDopplerDeployments = Record<string, Record<string, string>>

export const GENERATED_DOPPLER_DEPLOYMENTS = {
  "130": {
    "Airlock": "0x77ebfbae15ad200758e9e2e61597c0b07d731254",
    "Bundler": "0x91231cddd8d6c86df602070a3081478e074b97b7",
    "DopplerDeployer": "0x0d2f38d807bfad5c18e430516e10ab560d300caf",
    "DopplerLensQuoter": "0x82ac010c67f70bacf7655cd8948a4ad92a173cac",
    "GovernanceFactory": "0x99c94b9df930e1e21a4e4a2c105dbff21bf5c5ae",
    "LockableUniswapV3Initializer": "0xa3c847eab58eaa9cbc215c785c9cfbc19cdabd5f",
    "NoOpGovernanceFactory": "0x3ad727ee0fbbb8ee0920933fdb96f23fd56f1299",
    "NoOpMigrator": "0x917da361072ce968acd810bbfc9b64079426ebf0",
    "StreamableFeesLocker": "0x6ddfed58d238ca3195e49d8ac3d4cea6386e5c33",
    "TokenFactory": "0x43d0d97ec9241a8f05a264f94b82a1d2e600f2b3",
    "UniswapV2Migrator": "0xf6023127f6e937091d5b605680056a6d27524bad",
    "UniswapV3Initializer": "0x9f4e56be80f08ba1a2445645efa6d231e27b43ec",
    "UniswapV4Initializer": "0x4b0ec16eb40318ca5a4346f20f04a2285c19675b",
    "UniswapV4Migrator": "0x49f3fbb2dff7f3d03b622e3b2a6d3f2e6fdb2a5a",
    "UniswapV4MigratorHook": "0x53c050d3b09c80024138165520bd7c078d9e2000"
  },
  "1301": {
    "Airlock": "0x0d2f38d807bfad5c18e430516e10ab560d300caf",
    "AirlockMultisig": "0x40bcb4dda3bcf7dba30c5d10c31ee2791ed9ddca",
    "Bundler": "0xed344444633b965cd148f8ffce3765938a179094",
    "DopplerDeployer": "0x77b5f559ee9cf3bfcf2fff5731a84332d8eecac9",
    "DopplerLensQuoter": "0x917da361072ce968acd810bbfc9b64079426ebf0",
    "GovernanceFactory": "0x4225c632b62622bd7b0a3ec9745c0a866ff94f6f",
    "LockableUniswapV3Initializer": "0x9dfb775db7b005d9dc77da84d8b2e42c281d0344",
    "NoOpGovernanceFactory": "0x7e5d336a6e9e453c9f02e5102cc039e015fd8fb8",
    "NoOpMigrator": "0x193f48a45b6025dded10bc4baeef65c833696387",
    "StreamableFeesLocker": "0x1728e8b3282502f275949109331e070b819b38ea",
    "TokenFactory": "0x82ac010c67f70bacf7655cd8948a4ad92a173cac",
    "UniswapV2Migrator": "0x620e3fec244e913d73f2163623b62d02db69638b",
    "UniswapV3Initializer": "0xe0dc4012ac9c868f09c6e4b20d66ed46d6f258d0",
    "UniswapV4Initializer": "0x70d20cd48791e527036491dc464c8dc58351dd93",
    "UniswapV4Migrator": "0xb6d69eaa98e657beeff7ca4452768e6f707aa6b1",
    "UniswapV4MigratorHook": "0xfb0671ec46190b09255776d2d77744fa101ba500",
    "UniswapV4MulticurveInitializer": "0xac7939f1b4079d55a7fa4dfa314ac0173a77ba40",
    "UniswapV4MulticurveInitializerHook": "0x11b55a121a38fdab8faf16f9f1a4f124e3f42d40"
  },
  "4801": {
    "Airlock": "0x5f3ba43d44375286296cb85f1ea2ebfa25dde731",
    "GovernanceFactory": "0x136191b46478cab023cbc01a36160c4aad81677a",
    "TokenFactory": "0x5fbe931dc4b923a7abe4c47ad68d5bf9eda5b76d",
    "UniswapV2Migrator": "0x8b4c7db9121fc885689c0a50d5a1429f15aec2a0",
    "UniswapV3Initializer": "0x9916ec1c1e0462f6f8f7514e414f06bf001ac82a",
    "WETH": "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12"
  },
  "8453": {
    "Airlock": "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12",
    "Bundler": "0x136191b46478cab023cbc01a36160c4aad81677a",
    "DopplerDeployer": "0x49f3fbb2dff7f3d03b622e3b2a6d3f2e6fdb2a5a",
    "DopplerLensQuoter": "0x43d0d97ec9241a8f05a264f94b82a1d2e600f2b3",
    "GovernanceFactory": "0xa82c66b6ddeb92089015c3565e05b5c9750b2d4b",
    "LockableUniswapV3Initializer": "0xe0dc4012ac9c868f09c6e4b20d66ed46d6f258d0",
    "NoOpGovernanceFactory": "0x3ad727ee0fbbb8ee0920933fdb96f23fd56f1299",
    "NoOpMigrator": "0x6ddfed58d238ca3195e49d8ac3d4cea6386e5c33",
    "StreamableFeesLocker": "0x0a00775d71a42cd33d62780003035e7f5b47bd3a",
    "TokenFactory": "0x4225c632b62622bd7b0a3ec9745c0a866ff94f6f",
    "UniswapV2Migrator": "0x5f3ba43d44375286296cb85f1ea2ebfa25dde731",
    "UniswapV3Initializer": "0xaa47d2977d622dbdfd33eef6a8276727c52eb4e5",
    "UniswapV4Initializer": "0xed344444633b965cd148f8ffce3765938a179094",
    "UniswapV4Migrator": "0x166109c4ee7fe69164631caa937daa5f5cebfef0",
    "UniswapV4MigratorHook": "0x45178a8d6d368d612b7552b217802b7f97262000",
    "UniswapV4MulticurveInitializer": "0x65de470da664a5be139a5d812be5fda0d76cc951",
    "UniswapV4MulticurveInitializerHook": "0x892d3c2b4abeaaf67d52a7b29783e2161b7cad40"
  },
  "10143": {
    "Airlock": "0x5f3ba43d44375286296cb85f1ea2ebfa25dde731",
    "GovernanceFactory": "0x136191b46478cab023cbc01a36160c4aad81677a",
    "TokenFactory": "0x5fbe931dc4b923a7abe4c47ad68d5bf9eda5b76d",
    "UniswapV2Migrator": "0x8b4c7db9121fc885689c0a50d5a1429f15aec2a0",
    "UniswapV3Initializer": "0x9916ec1c1e0462f6f8f7514e414f06bf001ac82a",
    "WETH": "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12"
  },
  "57073": {
    "Airlock": "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12",
    "Bundler": "0x136191b46478cab023cbc01a36160c4aad81677a",
    "DopplerDeployer": "0xa82c66b6ddeb92089015c3565e05b5c9750b2d4b",
    "DopplerLensQuoter": "0x8af018e28c273826e6b2d5a99e81c8fb63729b07",
    "GovernanceFactory": "0xb4dee32eb70a5e55f3d2d861f49fb3d79f7a14d9",
    "TokenFactory": "0xfaafde6a5b658684cc5eb0c5c2c755b00a246f45",
    "UniswapV2Migrator": "0x5f3ba43d44375286296cb85f1ea2ebfa25dde731",
    "UniswapV3Initializer": "0xaa47d2977d622dbdfd33eef6a8276727c52eb4e5",
    "UniswapV4Initializer": "0x014e1c0bd34f3b10546e554cb33b3293fecdd056"
  },
  "84532": {
    "Airlock": "0x3411306ce66c9469bff1535ba955503c4bde1c6e",
    "AirlockMultisig": "0x852a09c89463d236eea2f097623574f23e225769",
    "BasicMultisig": "0x6f645fa08b7eadad620cec85634204b1d7a46dc2",
    "Bundler": "0xab7bacb0d5c2c10152f92d34e07f530eb3cb0fb1",
    "DopplerDeployer": "0x82d727ffda3f874da802663fc2f3f4b83dc3aaba",
    "DopplerLensQuoter": "0x4a8d81db741248a36d9eb3bc6ef648bf798b47a7",
    "GovernanceFactory": "0x9dbfaadc8c0cb2c34ba698dd9426555336992e20",
    "LockableUniswapV3Initializer": "0x16ada5be50c3c2d94af5feae6b539c40a78ad53c",
    "NoOpGovernanceFactory": "0x7bd798fafc99a3b17e261f8308a8c11b56935ea1",
    "NoOpMigrator": "0xf11066abbd329ac4bba39455340539322c222eb0",
    "StreamableFeesLocker": "0x3345e557c5c0b474be1eb4693264008b8562aa9c",
    "TokenFactory": "0x9d8fd79b2a59c5d91ccbd79c3aeb4de56451bb02",
    "UniswapV2Migrator": "0x04a898f3722c38f9def707bd17dc78920efa977c",
    "UniswapV3Initializer": "0x4c3062b9ccfdbcb10353f57c1b59a29d4c5cfa47",
    "UniswapV4Initializer": "0x832e4763deecb9941a768f2bbd18583219f018cc",
    "UniswapV4Migrator": "0xf326d8cdb65a4ad334cfbdd7d3a3cb27be8b770d",
    "UniswapV4MigratorHook": "0x9d0c38a80647e53d5a8a319b39de2b66b8586500",
    "UniswapV4MulticurveInitializer": "0x8099ef6a2100a5ac02af275eed606babd38a1689",
    "UniswapV4MulticurveInitializerHook": "0xf1a484724e2451d2c0290c946ec0034f057d6d40",
    "WETH": "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12"
  }
} as const
